### ISSUE TITLE
loss of style and function of print button in recent versions

### ISSUE THREAD

**Issue by pjv** [rlankhorst/zip-recipes-free#67]
Ever since this commit: #66 removed `{{ __('Print','zip-recipes') }}` from line 35 of `views/recipe.twig` and replaced with an empty `<a>` element, it has broken the preferred format and the functioning of the print button for a site I manage that uses Zip Recipes.

Is there a reason that the string was deleted from the link element?

I have hacked version 6.4.3 of ZR to add that string back and it fixes the print button for the site. Would it be possible to add that string back in future versions of ZR?

bump @rlankhorst (in case you hadn't seen this)

**Comment by rlankhorst** [comment]
@pjv indeed missed your message! I’ll look into it tomorrow and will get back to you on this.

**Comment by rlankhorst** [comment]
@pjv I've dropped the string because I wanted to limit the print button to the icon only. This works fine with the default settings as far as I can see. Do you have the icon hidden with css perhaps? What exactly is the styling issue you have?

I already have a release ready for today, so I can't do anything about it for this update. But we're currently working on a new update which offers the possibility to easily override the recipe template with your own. That should offer you the flexibility to add the "print recipe" string.

**Comment by pjv** [comment]
@rlankhorst Thanks for getting back to me. Yes, we are styling the recipe with our own CSS and have the Advanced option "Use Zip Recipes style" turned off. In that case, I believe that the plugin currently puts nothing usable  or style-able into the `.butn-link` element. The only content for that element is coming from the default Zip Recipes CSS.

I'll see if I can modify our custom CSS to inject content into that element so that it can function.

**Comment by rlankhorst** [comment]
@pjv if you can adjust the current recipe.twig after todays update, you're set for now. 

With the next update you can move the template to your own theme folder, and edit it there.

**Comment by rlankhorst** [comment]
@pjv just wanted to give you a heads up that the rewrite of the templating structure isn't finished yet, but we're going to do a minor update today, without the override option built in yet. 

For your setup, you can either skip this update, or copy over your template fix. My plan is to have the template rewrite ready for the next update.

**Comment by rlankhorst** [comment]
Hi @pjv, 

The version on Github here is the version we're about to release. It is a major restructuring of the plugin, making it ready for php 7.4, dropping twig as template engine, and working with overridable templates. We're trying to get as many users as possible to beta test it, for feedback and to track down any issue we haven't found yet.
